repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    # Should match pyproject.toml.
    rev: "23.3.0"
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    # Should match pyproject.toml.
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/python-poetry/poetry
    rev: "1.4.0"
    hooks:
      - id: poetry-check
  # TODO: re-enable after publishing 0.1.8
  #      - id: poetry-lock
  # TODO: land move then fix this stuff
  # - repo: https://github.com/pylint-dev/pylint
  #   rev: "v2.17.4"
  #   hooks:
  #     - id: pylint
  #       name: pylint
  #       entry: pylint
  #       language: system
  #       types: [python]
  #       require_serial: true
